apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  schedule: "0 0 * * 0"
  startingDeadlineSeconds: 300
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          containers:
            - name: django-clearsessions
              image: django_app_2
              imagePullPolicy: IfNotPresent
              env:
                - name: SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: django-secrets
                      key: SECRET_KEY
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: django-secrets
                      key: DATABASE_URL
              command:
                - "python"
                - "manage.py"
                - "clearsessions"
          restartPolicy: OnFailure
