apiVersion: v1
kind: Pod
metadata:
  name: django-clearsessions
spec:
  containers:
    - name: django-clearsessions-container
      image: django_app_2
      imagePullPolicy: IfNotPresent
      env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: SECRET_KEY
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: DATABASE_URL
      command:
        - "python"
        - "manage.py"
        - "clearsessions"
  restartPolicy: Never
