apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  template:
    spec:
      containers:
        - name: django-migrate
          image: django_app_2
          imagePullPolicy: IfNotPresent
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: SECRET_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: DATABASE_URL
          command:
            - "python"
            - "manage.py"
            - "migrate"
          tty: false
      restartPolicy: Never
